### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by privrja** [CoToDo/CoToDo#12]
- [x] Projít view napsat co tam bude potřeba
- [x] horni lista Create project, Create team, My teams, My projects
- [x] My projects - rozklikavaci jmeno projektu => presmerovani na project show,
- [x] Project show - show tasks, edit tasks, add subproject
- [x] My teams - rozklikavaci jmeno teamu => presmerovani na team show

**Comment by dusekpetr** [comment]
- horni lista Create project, Create team, My teams, My projects?, 
- My projects - rozklikavaci jmeno projektu => presmerovani na project show,
- Project show - show tasks, edit tasks, add subproject
- My teams - rozklikavaci jmeno teamu => presmerovani na team show
- Team show - roles, edit roles ....
