### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dusekpetr** [CoToDo/CoToDo#20]
- [x] notificate new work on task
- [x] notificate new comments
- [x] notificate adding to team
- [x] reopen task
- [x] delete team
- [x] edit role team
- [x] close task
- [x] show notification to user with some nice icon
- [x] email notifications
- [x] better view
- [x] mizeni notifikaci po rozkliknuti

**Comment by privrja** [comment]
Co vracet na link, když se provede delete team? Protože ten tým už potom neexistuje ... Dal sem tam zatim jméno týmu

**Comment by privrja** [comment]
přidat do DB entity indexy na user a datum?
