### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by dusekpetr** [CoToDo/CoToDo#37]
- [x] make labels
- [x] different colours for users
- [x] optional time metrics (minutes,seconds...)
- [x] ajax
- [x] bug with two workers
- [x] task line 389 bug

**Comment by privrja** [comment]
AJAX https://stackoverflow.com/questions/6395720/get-data-from-php-array-ajax-jquery#6395746

**Comment by privrja** [comment]
select u.mail, sum from (select user_id, SUM(strftime('%s', w.end_date) - strftime('%s', start_date)) sum from work w where w.task_id = 1 group by user_id) join app_users u on (user_id=u.id);
