### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by privrja** [CoToDo/CoToDo#39]
- [x] prozkoumat API
- [x] export users tasks to google drive
- [x] import users tasks from google drive
- [x] add login for google drive

**Comment by dusekpetr** [comment]
google Drive API

**Comment by privrja** [comment]
https://developers.google.com/drive/api/v3/quickstart/php

**Comment by privrja** [comment]
povoleni Google Drive API

`<a
 class="devsite-api-getstarted-widget button button-primary
          gc-analytics-event" data-henhouse-header-text="Enable the Drive API" data-henhouse-product-name="Quickstart" data-henhouse-credential-type="OAUTH" data-henhouse-client-type="OTHER" data-api-id="drive" data-category="Quickstart" data-action="Enable" data-label="Drive API, PHP">Enable the Drive API</a>`

**Comment by privrja** [comment]
https://developers.google.com/drive/api/v3/quickstart/php?refresh=1

**Comment by privrja** [comment]
https://developers.google.com/drive/api/v3/manage-uploads?refresh=1#simple

**Comment by privrja** [comment]
https://developers.google.com/api-client-library/php/auth/web-app?refresh=1
