### ISSUE TITLE
Exception pages

### ISSUE THREAD

**Issue by dusekpetr** [CoToDo/CoToDo#47]
Exception pages are located in templates/bundles/TwigBundle/Exception/error...html.twig
**Test on url: http://localhost:8000/index.php/_error/{statusCode} 
for example: (error 500) http://localhost:8000/index.php/_error/500**
- make graphic for all pages
- [x] error 404 page
- [x] error 500 page
- [x] all other errors

**Comment by Krostyna** [comment]
Added error pages and merge branch.
