### ISSUE TITLE
License

### ISSUE THREAD

**Issue by privrja** [CoToDo/CoToDo#6]
Neměli bychom zohledňovat licenci todo.txt?
https://github.com/todotxt/todo.txt

**Comment by MarekSuchanek** [comment]
No oni to mají sice pod GNU GPLv3 a některé ty projekty využívající formát taky... ale třeba

- https://github.com/infews/bulldog = MIT
- https://github.com/mjdescy/TodoTxtMac/blob/master/LICENSE.md = něco divného
- https://github.com/SverrirValgeirsson/Todour/blob/master/LICENSE = GPLv2
- https://github.com/sanpii/effitask = MIT

Jiné licenci ani nemají... a stejně jsou na tom webu... Jestli je vám to jedno, tak si dejte GPLv3, jinak klidně nechte MIT. Případně koukněte na https://choosealicense.com
